repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: master
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black
        language_version: python3
